[project]
name = "network-monitor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyside6>=6.8.1.1",
    "qasync>=0.27.1",
    "rich>=13.9.4",
]
